name: Manual Emergency Update
on:
  push:
    paths:
      - 'database.txt'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run Scraper
        run: python scripts/scraper.py
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "manual(data): оновлення графіків з тексту"
          file_pattern: "database.json"
